[build]
  publish = "public"

[functions]
  directory = "functions"

[[redirects]]
  from = "/admin/*"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[[redirects]]
 from = "/admin/*"
 to = "/.netlify/functions/redirect"
 status = 200
 force = true
